---
apiVersion: v1
kind: Secret
metadata:
  name: azure-storage-secret
  namespace: noobaa
type: Opaque
data:
  AccountName: <AZURE_ACCOUNT_NAME_BASE64>
  AccountKey: <AZURE_ACCOUNT_KEY_BASE64>
---
apiVersion: noobaa.io/v1alpha1
kind: BackingStore
metadata:
  labels:
    app: noobaa
  name: azure-blob-store
  namespace: noobaa
spec:
  type: azure-blob
  azureBlob:
    targetBlobContainer: <my-container>
    secret:
      name: azure-storage-secret
      namespace: noobaa
---
apiVersion: noobaa.io/v1alpha1
kind: BucketClass
metadata:
  labels:
    app: noobaa
  name: azure-bucket-class
  namespace: noobaa
spec:
  placementPolicy:
    tiers:
      - backingStores:
          - azure-blob-store
        placement: Spread
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  labels:
    app: noobaa
  name: <my-bucket-claim>
  namespace: noobaa
spec:
  additionalConfig:
    bucketclass: azure-bucket-class
  generateBucketName: <my-bucket-prefix>
  storageClassName: noobaa.noobaa.io
