---
apiVersion: networking.k8s.io/v1
controller:
    replicaCount: 4
    service:
        loadBalancerIP: 1.1.1.1
        annotations: {}
    publishService:
        enabled: true
    resources:
        requests:
            cpu: 250m
            memory: 256Mi
    config:
        proxy-body-size: 50m
        proxy-read-timeout: '600'
        proxy-send-timeout: '600'
tcp: {}
