---
masterKey: 
    ENC[AES256_GCM,data:JQQLm55T2ACUElzaC5uPYpiPXX87S+7J0t9Oyt6yCGs=,iv:8MBe3vc5AUBr8WrZqz2+Udk/mIWiNWQz5U1PdrDCzW0=,tag:Hp0YqyZb9Ab4tDBSjs7LMQ==,type:str]
teiAPIKey: 
    ENC[AES256_GCM,data:+KohOM12CxV+W7IfiWgH/R595Dc9IHtONPS11TlJ4Rdi6Rs=,iv:P+YNEIcl/52mhMVFY9SK1Kt7VkrOMpV9MUb26X6MjX0=,tag:OVr6XyyzMfcr3+cnh84dYA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:100874337694:key/c7fd5cab-3baf-40c1-a129-3d4a58c70cd3
          created_at: '2025-03-10T10:05:43Z'
          enc: 
              AQICAHhZfWILurHAsFqnvtAb0hx4XSK8Hq5vHmUDi3UArtcCpgGIV97UMtLzeGqSNg0HQWUeAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMwgQ8iP3Jbs5zuDvVAgEQgDtZ6ivenBOt67DqauQ5I4+M6nHP8MnilJWmScfLNgmipqA7bzCGTKU+yi0zGA08aSZJr/pbjdOpG23vkg==
          aws_profile: personal
    lastmodified: '2025-06-06T09:06:43Z'
    mac: 
        ENC[AES256_GCM,data:78I6rc4wVSSdh6+eKD7Rzap+5SBPLhuIp2U1eR6QHnQQ7OIf20ct9ag5bPfEM2WRj1YhKZ13SMKvm2Jb6ROB/L2dL5C/cOkyYN05pmfqn9zH/PxxpPTZLB1+3kqWm2wI36OH58itXsSvKTZju0QD3MmQ++ZABV/aBWyem/xxB+4=,iv:AOvh/+aUxjT4vfgKpDUktkImbbwoqJZHEAD6RUT88V0=,tag:OJ9kaiG97wYRT13NbqBnYA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
