---
adminPassword: 
    ENC[AES256_GCM,data:F52JZ0Os/QKoQa84x6ShxXj3gueb4benEnf/be1j0WS1,iv:wXhOFri7jV+XMafNYNLAUBIhQ7md8bwd9bCh5ZqTay8=,tag:PEGSL3Ug47CsrzMzRaqH/w==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:100874337694:key/c7fd5cab-3baf-40c1-a129-3d4a58c70cd3
          created_at: '2025-05-23T12:38:34Z'
          enc: 
              AQICAHhZfWILurHAsFqnvtAb0hx4XSK8Hq5vHmUDi3UArtcCpgFu+sMPQaJMgAqhUGG9fUSiAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM86y2kSmZehLKDcrtAgEQgDuksLUeosY5b5LTPPb+LhNrnoPaRGdS27W96hvGBApiFBrv3gX+1hZV8XAzu8neUeKv9rSTucLVsm2h5Q==
          aws_profile: personal
    lastmodified: '2025-05-23T12:38:35Z'
    mac: 
        ENC[AES256_GCM,data:5mvtzHEXY29Nf23Tt5Og7OnzHI1WrajKGABeXkIxDUJHb87ZswBtDPuJS/LB24l1b23vRkPeEjTgR4+lRgDcdCHFl/+6qVsqUS4l8WzzSnK9FPoRLoPP5l3lPzChpbSWZQXep9CCzYWzzw6SlIKXExFuqOyr3GZnOmUL2fFgjcY=,iv:ltpyCcQZRJ8J7a7VE1S1jfExltVUB/vNsCrkAOwZqOU=,tag:Ue3rJ3sTBpkH8N8mkshGgQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.1
