---
apiKey: 
    ENC[AES256_GCM,data:qjY3Mn3L/KhsrQEsRI+/2U0YzoQr0liCFnRsRzF2fPrlda8=,iv:V3hs3SuAhQA8abj4IsgIZtm0YH0W8U0QVsk8SDa35Ec=,tag:4UWSH0BqP3fKB3a9quKJlg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:100874337694:key/c7fd5cab-3baf-40c1-a129-3d4a58c70cd3
          created_at: '2025-07-09T12:52:51Z'
          enc: 
              AQICAHhZfWILurHAsFqnvtAb0hx4XSK8Hq5vHmUDi3UArtcCpgFS0O6mTHE1hi343xKHGDbOAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMc4aJfXoziY9XKA3XAgEQgDtFhvM6y150BU0Gmiv/rFDeBX4NZCIsFM6/imGMKtD+Nc2+FHK2/UsesXF7bbkdkpTFtbyhKZh3XCGP0w==
          aws_profile: personal
    lastmodified: '2025-07-09T12:52:51Z'
    mac: 
        ENC[AES256_GCM,data:gW3b3Iwmou+TD555uanv3qbtNSZvcMrWXdnjOTee+tJQje6WrLEUYnv4k8f7JuI3/7biPbBpLWGDxD39rLFLe+HTDP1boyoWhJ3yHXdevkYtX1r2KUJKFeiSnCYlkgNI3a5z0OcCS1mn4UmmTYd3hzIfzWpkT9XKeKmQNsh6YKM=,iv:YQcfxrZ5Z0tMz0qSuX/ASooFM/Xymhh2P4jTtyKa7SA=,tag:e9DIZXVZPdJB7/Qlbq3oiQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
