---
auth: 
    ENC[AES256_GCM,data:49smbyGO6UHvw/VFrannk9Yu1Eix2dCEXcBOWKcHmKKz1bkL+POXiJkA,iv:U1+HnXZKXqS919etms46sL6GkBNZaH21P0YoE92XSJQ=,tag:UKHtWI8oux+4rRHs2jhFZA==,type:str]
hf_token: 
    ENC[AES256_GCM,data:OtQ8bfDDv23xokvvZoHyPIrZb7TGTm0TvSTTA9z3N4k4F6qheg==,iv:kiPfg9YhJ47mvjShTubW63dBoVgA75nfsLLC/6e+X48=,tag:+k6Dn1qQzHNd6ilW9FlH9Q==,type:str]
dummy_password: 
    ENC[AES256_GCM,data:QTbRBJBoEq55eMh7Lwor1o8Qt1b2oPu9VxH4o22hFEmU,iv:1f/paQ6pCfVA1/1m9Y9y6H2VGD7vP35jKJP2BPbYJWE=,tag:m3gvnTMQGWO1m1JTQ8BhhA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:100874337694:key/c7fd5cab-3baf-40c1-a129-3d4a58c70cd3
          created_at: '2025-05-06T10:31:47Z'
          enc: 
              AQICAHhZfWILurHAsFqnvtAb0hx4XSK8Hq5vHmUDi3UArtcCpgHePyCY2p6xFY6q2ZU65xQ/AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMj+pFaYz5zGY/J8mmAgEQgDuLCJoxczJfvLwQ1SnX3dmFvtEUA191lXxcp+ZIbwLI6IyYU9yd9myJmbvtNG9ZD0HKtz9Z4Zg+O6QMSQ==
          aws_profile: personal
    lastmodified: '2025-05-06T10:34:05Z'
    mac: 
        ENC[AES256_GCM,data:BTzfVsIdrSoXBbiuRUSgYlNr2704SKm1kfJmmMSEym4sTe1z1XhknuRN3Ag9eLYBwE5zesfDUJEl0uQ13mQ2PtnfC+K8sJa1PuNVcjeI08ZFctuHy7fLZU+9FJ2/T5ujt04r5eefWS3Ov1pT6PxZMBdHwH+9sMoXxDhIEl6oei4=,iv:xjoAlNcoXUPy35QxFiW+hdzx4aXo+/n0D4nr/XCcqNQ=,tag:7lIHD9UzjN+YlGFe0pCtwQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.1
