OPENAI_API_KEY: ENC[AES256_GCM,data:6IXV1Xj+dTiy/B35X26mglwEtIKCW0d8ckO483rLG8fx3sSwLcyA343jnFFEj2tKtNbl,iv:OCgZe3Cvd6xQI0fVQk3tAhNehNX0q5vmJHwauHVXhU8=,tag:XI/ZE1PxtWpYDdfcoxh+SQ==,type:str]
dummy: ENC[AES256_GCM,data:Hg4AlPiFc/z1C3ht1vtbP+07Kq5DwmjHZMEoWWzpsWQ=,iv:cxZlEFCguMALLJiBRJS0Wi+E0yT5lR7r7aIkDjxJSso=,tag:mNvGXDJUZSf0J5hpMhRG5Q==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:100874337694:key/c7fd5cab-3baf-40c1-a129-3d4a58c70cd3
          created_at: "2025-02-28T17:20:25Z"
          enc: AQICAHhZfWILurHAsFqnvtAb0hx4XSK8Hq5vHmUDi3UArtcCpgFi60qsuq4EnE15WKrAwN3aAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMUTRzeia97+5vIAZ1AgEQgDtjK3HJpR6yFthhKmTOvW9f67sSkPYOQclMUMHJ3nuunEU/vh6BQV9fY/OFXFRwwQ0VOE0UAy7T4Wxwig==
          aws_profile: personal
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-02-28T17:20:26Z"
    mac: ENC[AES256_GCM,data:OPF36CfdKOa4liQSs6awNxxoEz7tgieWi7+NWKFubkdb/5mqsLKRodSJ21kXGB++nh/NZY0OxU+HrDv/id0YqHmpEQUMKJyfSMtTM29akMB7hohmPlBoPOd95MXQ1NKAHZ7vrubZV/3bnl9hnd5uPL9KMBAe5ubD1GiXdCVsRTE=,iv:gQ7/8ykCS4CwKlJKT139xklwKBHhtVEaIWnzOUoU3m0=,tag:Pnvn/+UucOtKjGSVp8CPtw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
